export enum RiskRuleType {
  TRANSACTION_AMOUNT = "TRANSACTION_AMOUNT",
  TRANSACTION_VELOCITY = "TRANSACTION_VELOCITY",
  MERCHANT_VOLUME = "MERCHANT_VOLUME",
  ADDRESS_BLACKLIST = "ADDRESS_BLACKLIST",
  COUNTRY_BLOCK = "COUNTRY_BLOCK",
}
