export enum AuditAction {
  REFUND_INITIATED = "REFUND_INITIATED",
  REFUND_RETRIED = "REFUND_RETRIED",
  SETTLEMENT_MANUALLY_TRIGGERED = "SETTLEMENT_MANUALLY_TRIGGERED",
  SETTLEMENT_RETRIED = "SETTLEMENT_RETRIED",
  SETTLEMENT_PUT_ON_HOLD = "SETTLEMENT_PUT_ON_HOLD",
}
