export enum RefundMethod {
  CRYPTO_ONCHAIN = "CRYPTO_ONCHAIN",
  FIAT_DEDUCTION = "FIAT_DEDUCTION",
}

export enum RefundStatus {
  INITIATED = "INITIATED",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum RefundReason {
  CUSTOMER_REQUEST = "CUSTOMER_REQUEST",
  FRAUD = "FRAUD",
  DUPLICATE = "DUPLICATE",
  COMPLIANCE = "COMPLIANCE",
  MERCHANT_ERROR = "MERCHANT_ERROR",
  OTHER = "OTHER",
}
