export enum MaintenanceType {
  PLANNED_DOWNTIME = 'PLANNED_DOWNTIME',
  PARTIAL_DEGRADATION = 'PARTIAL_DEGRADATION',
  EMERGENCY = 'EMERGENCY',
  INFRASTRUCTURE_UPGRADE = 'INFRASTRUCTURE_UPGRADE',
}

export enum MaintenanceStatus {
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AnnouncementType {
  INFO = 'INFO',
  WARNING = 'WARNING',
  MAINTENANCE = 'MAINTENANCE',
  INCIDENT = 'INCIDENT',
  RESOLVED = 'RESOLVED',
}

export enum AnnouncementAudience {
  ALL_MERCHANTS = 'ALL_MERCHANTS',
  SPECIFIC_MERCHANTS = 'SPECIFIC_MERCHANTS',
  SPECIFIC_TIERS = 'SPECIFIC_TIERS',
  INTERNAL_ONLY = 'INTERNAL_ONLY',
}
