export enum ComplianceReportType {
  TRANSACTION_REPORT = 'TRANSACTION_REPORT',
  MERCHANT_DUE_DILIGENCE = 'MERCHANT_DUE_DILIGENCE',
  AML_SUMMARY = 'AML_SUMMARY',
  FEE_REPORT = 'FEE_REPORT',
  SETTLEMENT_REPORT = 'SETTLEMENT_REPORT',
}

export enum ReportFormat {
  CSV = 'CSV',
  XLSX = 'XLSX',
  PDF = 'PDF',
}

export enum ComplianceReportStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
